footstone:
  datasource:
    enabled: true

logging:
  level:
    com.olasharing: DEBUG

eureka:
  client:
    registryFetchIntervalSeconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

server:
  port: 8081
